---
title: "Pollsters"
author: "Jake"
date: "5/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

538 Ratings from <https://projects.fivethirtyeight.com/pollster-ratings/>

## Marist College
* 538 Rating: A+
* Methodology in general: <http://maristpoll.marist.edu/methods/#sthash.kbYzsqHj.dpbs>
    - Samples designed for adult >18 population
    - Random-digit-dialing, geographically stratified proportional to population
    - Includes mobile phones
    - Member of AAPOR's Transparency Initiative
        - Can contact for additional questions
* How do they define likely / registered voter?
    - Report for registered and / or likely voters
    - Probability turnout model for likely voters
        - Determines likelihood respondents will vote in current election based upon their chance of vote, interest in election, past election participation
        - Does *not* weight by party ID
* How do they do weighting? (before / after reporting results)
    - Data cleaned and combined to balance population parameters using stat software
    - Balances to reflect Census results for age, gender, income, race, and region
* Unclear how to get spreadsheet version of poll results --- follow up later
    
## Monmouth University
* 538 Rating: A+
* Methodology in general
    - Roughly 60% cell phone, 40% landline, all live interview (no robo-calls)
    - Charter member of AAPOR Transparency Initiative
* How do they define likely / registered voter?
    - Likely Voters: Asks participants to identify themselves with the following question: "How likely is it that you will vote in the November election – are you certain to vote, likely to vote, are you not sure, or are you unlikely to vote?"
    - Registered voters depends on the poll. (2 reoccurring cases)
        1. Asks randomly sampled (via phone-line) participants if they are registered voters. 
        2. Registered voters pulled from list of voters who participated in a primary or general election in the 2016 or 2018 election cycles or have registered to vote since November 2018
* How do they do weighting? (before / after reporting results)
    - The full sample is weighted for region, age, education, gender and race based on US Census information 
    - <https://www.monmouth.edu/polling-institute/reports/?s=election>
    
    
## ABC News / The Washington Post
* 538 Rating: A+
* Overview of standards: <https://abcnews.go.com/US/PollVault/abc-news-polling-methodology-standards/story?id=145373>
* Archive: <https://www.washingtonpost.com/polling/2019/05/24/washington-post-poll-archive/>
* Crosstabs: Published as google spreadsheet
* How do they define likely / registered voter?
    - Apply likely voter models before publishing once we get closer to election day
    - Crosstabs: Party ID, Sex, Ideology, Age, Education, Race / Sex / Ed Cross, etc.
* How do they do weighting? (before / after reporting results)
    - Weighting completed before reporting
    
## Siena College / The New York Times Upshot
* 538 Rating: A+
* Methodology in general: <https://www.nytimes.com/2018/09/06/upshot/live-poll-method.html> 
    - Telephone numbers were selected from an L2 (private voter and model issued data provided) voter file stratified by age, region, gender, party, race and turnout in 2014.
    - Voters were contacted on cellular and landline telephones. Interviewers asked for the person named on the voter file, and ended the interview if the intended respondent was not available.
    - Charter Member of AAPOR's Transparency Initiative
* How do they define likely / registered voter?
    - Only call people on file as registered voters (according to L2's data)
    - Final turnout score is 56 percent turnout model and 44 percent self-report, based on a model of validated turnout in prior Upshot/Siena polls
* How do they do weighting? (before / after reporting results)
    - The sample is weighted to match Upshot estimates for the composition of the likely electorate by age, race, region, turnout, party, gender and education.
    - The party weight is partisan primary vote history or party registration, or, in the states where neither is available, a model of likely support for Donald J. Trump in the 2016 presidential election.
    - Voter file data is used for weighting, except for education.
    
## Selzer & Co.
* 538 Rating: A+
* Links to polls: <https://www.grinnell.edu/poll/methodology>
* How do they define likely / registered voter?
    - Unclear how they do likely voters
* How do they do weighting? (before / after reporting results)
    - Weighted before publishing
    - Weighted by sex, age, race, education (based on census)

## Muhlenberg College
* 538 Rating: A+
* Methodology in general: <https://www.muhlenberg.edu/feb2020election/> 
    - Quality control mechanisms include multiple call-backs, survey pre-testing, and data entry verification 
    - Exclusively live-caller telephone polls
    - Charter Member of AAPOR's Transparency Initiative
* How do they define likely / registered voter?
    - Registered voters are determined by state files
    - Likely voter is defined as registered voters who have either
        + voted in at least 2 of the last 4
general elections 
        + or who had voted in either the 2018 primary elections or 2017 general election
        + or if they were a new registrant since the 2016 Presidential Election
* How do they do weighting? (before / after reporting results)
    - Data is weighted to gender, age, region, party, race and educational attainment to reflect voter population parameters.
    
## SurveyUSA
* 538 Rating: A
* Methodology in general
    - Sometimes 100% by telephone; in some cases, 100% online; and in other cases, a blend of the two.
    - Landlines are interviewed using both live interviews and prerecorded robo-calls.
    - The youngest male is requested on approximately 30% of calls to home phones, the youngest adult is requested on approximately 70% of calls. 
* How do they define likely / registered voter?
    - Asks respondents if they are registered voters
    - Likely classification depends on survey (2 reoccurring cases)
        1. Asks respondents if they are certain to vote, certain to not, unlikely, or likely to vote. Likely voters  were categorized as only those that responded "100% certain to vote". "Probably will vote" responses were not considered likely voters." Ex: <http://www.surveyusa.com/client/PollReport.aspx?g=4b9bd0e5-3f07-4da9-b86f-370c0255240e>
        2. Of a poll that asks if they will vote... likely voters were categorized as those that responded "almost certain","100% certain", "already returned ballot" Ex: <http://www.surveyusa.com/client/PollReport.aspx?g=61197540-a792-49f0-9889-4dca5ad251ee>
* How do they do weighting? (before / after reporting results)
    - responses are minimally weighted to U.S. Census targets or voter file targets for gender, age and race. Cell (target) weighting is used.
    - <https://www.surveyusa.net/methodology/>
    
## Strategic Vision LLC
* 538 Rating: F
* Methodology in general 
    - AAPOR was unable to obtain info about who sponsored the survey; who conducted it; a description of the underlying sampling frame; an accounting of how “likely voters” were identified and selected; response rates; and a description of any weighting or estimating procedures used. <https://www.aapor.org/Communications/Press-Releases/AAPOR-Raises-Objections-to-Actions-by-Atlanta-Base.aspx>
* How do they supposedly use likely/register voters?
    - A poll from 2008 reports "600 likely Republican primary voters and 600 likely Democratic primary voters, aged 18+, and conducted January 4-6, 2008". This is the only methodological statement for the whole poll. <https://www.realclearpolitics.com/articles/docs/SV_NH08.html>
