---
title: "Links"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## House Effects
* Nate Silver, FiveThirtyEight
    - How 538 does pollster house effects
    - <https://fivethirtyeight.com/features/calculating-house-effects-of-polling-firms/>

## General Election Modeling
* Elliott Morris, The Economist
    - Hierarchical modeling, demographics, inferring state polls from national
    - <https://t.co/OTgETLG2wp>
    - Looks to be behind a paywall --- should check with UPS (Eli Gandour-Rood) to see if they have an Economist subscription we can access
    - Read by Jake - No
    - Read by Haley - Yes
* Elliott Morris, The Economist
  - Toy election simulator
  - <https://github.com/elliottmorris/toy-us-election-simulator#toy-us-election-simulator>
  - Read by Jake - No
  - Read by Haley - Yes
* Andrew Mercer, Pew Research Center
  - Margin of Error in Election Polls
  - <https://www.pewresearch.org/fact-tank/2016/09/08/understanding-the-margin-of-error-in-election-polls/>
  - Read by Jake - No
  - Read by Haley - Yes

## Important Voter Groups 
* Ariel Edwards-Levy, Huffington Post
  - Importance of undecided/unsure voters
  - <https://www.huffpost.com/entry/2020-polls-voters-undecided_n_5dcdda2fe4b0294748142dff>
  - Read by Jake - No
  - Read by Haley - Yes  
* Harry Enten, CNN Politics
  - The difference between "double haters" in 2016 and 2020 elections
  - <https://www.cnn.com/2020/05/13/politics/voters-biden-trump-2020-analysis/index.html>
  - Read by Jake - Yes
  - Read by Haley - Yes

## Polling Methodology
* Nathanial Rakich, FiveThirtyEight
  - How to read 2020 polls intelligently
  - <https://fivethirtyeight.com/features/how-to-read-2020-polls-like-a-fivethirtyeighter/>
  - Read by Jake - Yes
  - Read by Haley - Yes
* Nate Cohn, NY Times/The Upshot
  - Suggests sampling errors have been improved (but not perfected) since 2016
  - <https://www.nytimes.com/2020/05/12/upshot/polls-2020-trump-biden.html>
  - Read by Jake - Yes
  - Read by Haley - Yes
* Clare Malone, FiveThirtyEight
  - Looks at what makes a good pollster and when shocking data isn't an outlier - but the start of a new trend
  - <https://fivethirtyeight.com/features/selzer/>
  - Read by Jake - No
  - Read by Haley - No
* Nate Silver, FiveThirtyEight 
  - More in depth explanation of pollster ratings and pollster methods
  - https://fivethirtyeight.com/features/how-fivethirtyeight-calculates-pollster-ratings/
  - Read by Jake - No
  - Read by Haley - No
* Nathaniel Rakich, FiveThirtyEight
  - Explanation of polling error coming into 2020 election 
  -<https://fivethirtyeight.com/features/weve-updated-our-pollster-ratings-ahead-of-the-2020-general-election/>
  - Read by Jake - No
  - Read by Haley - No  
* Pollster Fraud (By Strategic Vision LLC), FiveThirtyEight
  - Creates the case for Strategic Vision's pollester fraud and what that looks like
  - <https://fivethirtyeight.com/features/strategic-vision-polls-exhibit-unusual/>
  - Read by Jake - No
  - Read by Haley - Yes
* AAPOR's review of Strategic Vision LLC,AAPOR
  - AAPOR expresses concern over lack of transparency of Strategic Vision's polling practices and reports they are in violation of the association’s Code of Professional Ethics and Practices.
  - Read by Jake - No
  - Read by Haley - Yes
* AAPOR
  - Links to standard definitions/recommendations for polling practices. (might be a little long to read all of it, but good reference point.)
  -<https://www.aapor.org/Standards-Ethics/Standard-Definitions-(1).aspx>
  - Read by Jake - No
  - Read by Haley - No   

## Other Names / Sites for starting to look for articles
* David Byler
    - Washington Post
* Ariel Edwards-Levy
    - Huffington Post Political
    - Public Opinion Polling
* Nate Silver
    - FiveThirtyEight
* Nate Cohn
    - Upshot
* Dave Wasserman
    - Cook Political Report
* Harry Enten
* Geoffrey Skelley
    - FiveThirtyEight
* Sean Trende
    - Real Clear Politics
* Larry Sabato
    - Sabato's Crystal Ball
    
    
    
    
## Academic Articles
* Election forecasting: Principles and practice
    - MS Lewis-Beck
    - <https://journals.sagepub.com/doi/abs/10.1111/j.1467-856X.2005.00178.x>
* Polls and Votes: The Trial-Heat Presidential Election Forecasting Model, Certainty, and Political Campaigns
    - J. E. Campbell
    - <https://journals.sagepub.com/doi/abs/10.1177/1532673x9602400402>
* Election forecasting for turbulent times
    - MS Lewis-Beck, C Tien
    - <https://www.cambridge.org/core/journals/ps-political-science-and-politics/article/election-forecasting-for-turbulent-times/3B2AC3B0805D0F217DA35A396217BD94>
* US presidential election forecasting: An introduction
    - MS Lewis-Beck and J.E. Campbell
    - <https://www.acsu.buffalo.edu/~jcampbel/documents/IJF1Intro_000.pdf>
* Us presidential election forecasting: Introduction
    - MS Lewis-Beck and M Stegmaier
    - <https://www.cambridge.org/core/journals/ps-political-science-and-politics/article/us-presidential-election-forecasting/B8BF256F7E59D68305CA6040ABF03D90>
